### ISSUE TITLE
Undefined method `response' for #<OpenSSL::SSL::SSLError:...

### ISSUE THREAD

**Issue by andresmontelpare** [SandyChapman/fastlane-plugin-jira_versions#1]
_**_I am getting this error when i run create o release jira version._**_
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-plugin-jira_versions-0.1.0/lib/fastlane/plugin/jira_versions/actions/create_jira_version.rb:58:in `rescue in run': [!] undefined method `response' for #<OpenSSL::SSL::SSLError:0x007f832e27de28> (NoMethodError)
Did you mean?  respond_to?
Did you mean?  respond_to?
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-plugin-jira_versions-0.1.0/lib/fastlane/plugin/jira_versions/actions/create_jira_version.rb:9:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:186:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:186:in `execute_action'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from ../fastlane/Fastfile:6:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/commands_generator.rb:69:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.54.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/commands_generator.rb:257:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/commands_generator.rb:31:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.107.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Here my env:**

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G1004)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios
platform :ios do

desc "Create a new JIRA version for the next build"
lane :create_version do
  version_id = create_jira_version(
    url: 'https://jira.etermax.com',
    username: 'andres.montelpare',
    password: 'your_jira_password', 
    project_name: 'SPRIT', 
    name: "iOS 0.1.1",
    description: 'Fastlane auto-created version'
  )
end

  lane :releaseJiraVersion do
    # Asegura que estemos en master.
    #ensure_git_branch
  version_id = release_jira_version(
    url: 'https://jira.etermax.com',
    username: 'andres.montelpare',
    password: 'your_jira_password', 
    project_name: 'SPRIT', 
    name: "0.1.1",
  )

  end 
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.107.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.54.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                        | Version | Update-Status |
| ----------------------------- | ------- | ------------- |
| fastlane-plugin-jira_versions | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version |
| ----------------------------- | ------- |
| did_you_mean                  | 1.0.0   |
| highline                      | 1.7.8   |
| commander                     | 4.4.0   |
| terminal-table                | 1.4.5   |
| json                          | 1.8.3   |
| multipart-post                | 2.0.0   |
| faraday                       | 0.9.2   |
| faraday_middleware            | 0.10.0  |
| dotenv                        | 2.1.1   |
| net-ssh                       | 3.2.0   |
| net-sftp                      | 2.1.2   |
| plist                         | 3.1.0   |
| rubyzip                       | 1.1.7   |
| security                      | 0.1.3   |
| krausefx-shenzhen             | 0.14.10 |
| slack-notifier                | 1.5.1   |
| rouge                         | 1.11.1  |
| xcpretty                      | 0.2.4   |
| terminal-notifier             | 1.7.1   |
| word_wrap                     | 1.0.0   |
| bundler                       | 1.13.6  |
| colored                       | 1.2     |
| credentials_manager           | 0.16.2  |
| multi_xml                     | 0.5.5   |
| http-cookie                   | 1.0.3   |
| faraday-cookie_jar            | 0.0.6   |
| fastimage                     | 1.6.8   |
| mini_magick                   | 4.5.1   |
| i18n                          | 0.7.0   |
| thread_safe                   | 0.3.5   |
| tzinfo                        | 1.2.2   |
| activesupport                 | 4.2.7.1 |
| multi_json                    | 1.12.1  |
| babosa                        | 1.0.2   |
| excon                         | 0.54.0  |
| gh_inspector                  | 1.0.2   |
| fastlane_core                 | 0.54.0  |
| io-console                    | 0.4.5   |
| CFPropertyList                | 2.3.3   |
| claide                        | 1.0.1   |
| xcodeproj                     | 1.4.1   |
| xcpretty-travis-formatter     | 0.0.4   |
| oauth                         | 0.5.1   |
| jira-ruby                     | 1.1.2   |
| fastlane-plugin-jira_versions | 0.1.0   |
</details>

*generated on:* **2016-11-09**
</details>

**Comment by faken** [comment]
I've created a PR (#2) to control whether to use HTTPS for communication with the JIRA API. 
Try again with disabled HTTPS.
